### ISSUE TITLE
Dataset in CoronaWhy Dataverse

### ISSUE THREAD

**Issue by geek80** [anag004/covid-model#1]
Hello,Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse  as a piece of common COVID-19 dataframe http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/3QPTTQ

Would you be willing to help with maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for medical science community.

**Comment by tyagiutkarsh** [comment]
The datasets are available via their respective open-source links. We have used The John Hopkins CSSE COVID19 repository, covid19india tracker project API, and Google social mobility reports. You may follow the links in README for relevant sources.
We do not own nor update any part of the data manually.
